### ISSUE TITLE
Custom password for mongo or redis password is not injected into api, els, das

### ISSUE THREAD

**Issue by krokofant** [featbit/featbit-charts#21]
The connectionstrings are not updated in any way to reflect the password that's been set.

With configuration like:
```yaml
      mongodb:
        enabled: true
        auth:
          enabled: true
          existingSecret: passwords
      redis:
        enabled: true
        auth:
          enabled: true
          existingSecret: passwords
```

Is there a workaround available for this? Would an acceptable approach be to override the connection string directly? Or can the password be injected by some other environment variable to the services?

Edit: If auth is disabled, mongodb is configured to be used without a password, but the connection strings still specify the password as the default "password". So one must explicitly specify enable auth and then set `rootPassword` to `password`.
