### ISSUE TITLE
Support dnsConfig for pods

### ISSUE THREAD

**Issue by krokofant** [featbit/featbit-charts#35]
I'd like to be able to change the `dnsConfig` and underlying `ndots`. Please expose this as a configurable object.

Example configuration:
```yaml
# ...
dnsConfig:
  options:
    - name: ndots
      value: "2"
containers:
# ...
```
