### ISSUE TITLE
Missing nodeSelector in DAS test connection

### ISSUE THREAD

**Issue by krokofant** [featbit/featbit-charts#44]
Everything except the [DAS test connection](https://github.com/featbit/featbit-charts/blob/8d4b7e6fa0a6a141dbe46d3dec4ed0f1529fce72/charts/featbit/templates/tests/das-test-connection.yaml) supports nodeSelector.

Example for, perhaps, everything else:
```yaml
ui:
  nodeSelector: { "kubernetes.io/os": "linux", "foo": "bar" }
api:
  nodeSelector: { "kubernetes.io/os": "linux", "foo": "bar" }
els:
  nodeSelector: { "kubernetes.io/os": "linux", "foo": "bar" }
das:
  nodeSelector: { "kubernetes.io/os": "linux", "foo": "bar" }
mongodb:
  nodeSelector: { "kubernetes.io/os": "linux", "foo": "bar" }
redis:
  master:
    nodeSelector: { "kubernetes.io/os": "linux", "foo": "bar" }
```
