### ISSUE TITLE
How to define prefix path based ingress using single hostname for UI, API, ELS(evaluation server)

### ISSUE THREAD

**Issue by rajnekkanti** [featbit/featbit-charts#46]
sample configuration that we defined currently, Is there an example or sample documentation for this?

ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    path: "/featbit/ui(/|$)(.*)"
    pathType: "Prefix"
    host:

ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    path: "/featbit/api(/|$)(.*)"
    pathType: "Prefix"
    host:

ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    path: "/featbit/els(/|$)(.*)"
    pathType: "Prefix"
    host:

**Comment by dsun0720** [comment]
here is an example that we ever tested in gks, you can changed it based your own k8s context

```yaml
apiExternalUrl: "https://api.featbit.fyi"
evaluationServerExternalUrl: "https://els.featbit.fyi"

global:
  ingressClassName: ""

ui:
  ingress:
    enabled: true
    host: "www.featbit.fyi"
    path: "/"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: "featbit-ui-global-ip"
      networking.gke.io/managed-certificates: "fb-managed-cert"

api:
  ingress:
    enabled: true
    host: "api.featbit.fyi"
    path: "/"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: "featbit-api-global-ip"
      networking.gke.io/managed-certificates: "fb-managed-cert"

els:
  ingress:
    enabled: true
    host: "els.featbit.fyi"
    path: "/"
    pathType: "Prefix"
    annotations:
      kubernetes.io/ingress.global-static-ip-name: "featbit-els-global-ip"
      networking.gke.io/managed-certificates: "fb-managed-cert"

```
