### ISSUE TITLE
Unable to set initContainer SecurityContext.

### ISSUE THREAD

**Issue by clbiggs** [featbit/featbit-charts#51]
We run our environment under the restricted pod security policy. With this the initContainers need to have their securityContext set as well with the main container.

**Comment by dsun0720** [comment]
Hello @clbiggs Please clarify which level of security context you need, for the pod or for the container?

if you need that in the level of pod, we have `podSecurityContext` for each service.

Using the API as an example：

```yaml
api:
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
...
```
